[package]
name = "crank-convert"
version = "0.1.0"
edition = "2021"

[features]
default = ["native"]
# The "native" trait defines whether to use multithreading and std::Fs. Leave it off for webassembly
native = []

[dependencies]
lazy_static = "1.4.0"
phf = { version = "0.10", features = ["macros"] }
convert-proc = { path = "../convert-proc" }
thiserror = "1.0"
simple_logger = "2.1"
log = "0.4"